repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.394
    hooks:
      - id: pyright
        additional_dependencies:
          [
            "aiohttp==3.9.1",
            "aiodns==3.1.1",
            "yarl==1.18.3",
            "multidict==6.1.0",
            "discord.py==2.4.0",
            "beautifulsoup4==4.13.3",
            "aiosqlite==0.21.0",
          ]
